### PR TITLE
add simple Etag function (304 not modified) 

### PR DESCRIPTION
**Pull request by bazi12**
I added simple Etag. (status code : 304 not modified)
As we needed to fix staticServe, we also modified private / http a bit.

If it is set to not trace with safari, Etag does not work but it is normal operation.
(safari Request header DNT: 1)

I put etags.nim in middleware, it might be the reference from http.nim became unnatural :(

### CODE REVIEW

**Comment by 2vg** [comment]
Thank you very much for the great pull requests! !

However, sorryly, since mofuw now can be optimized further from the viewpoint of memory operation, I am redesigning it from almost first.

I have not pushed to the devel branch yet.

So ... I can not merge until the newly designed mofuw is ready.

I will inform you when I am ready, so submit another pull request at that time!!

Big thanks bazi ♡

Ah, the pull request does not have to be closed.(either will do ;) )

**Comment by bazi12** [comment]
OK, I will send again :)
good server !

**Comment by 2vg** [comment]
@bazi12 Well, redesign is complete.

Let's create etag as private / etag.nim, not middleware.
Since etag is built directly into http, I think that it is not appropriate as middleware :)

\- EXTRA \-
Having a pool of contexts, and tremendous performance improvements were seen by reducing wasteful memory operations by significantly changing buffer handling.

The pipeline benchmark is about 1.4 times the previous mofuw in my result;) (250k req -> 350k req)

**Comment by bazi12** [comment]
awesome . great performance !
I will try it soon :)

**Comment by bazi12** [comment]
Sorry, misstake .
I will send you a pull request with a new branch !

**Pull request closed without merging**
